Master
tedious/Fetch pull request #184
Opened 2016-11-15 20:53 UTC by deemyboy

Fixed empty subject error from Message.php

2016-12-01 07:45 UTC, sergeyklay requested changes

2016-12-01 07:45 UTC, sergeyklay commented on README.md
> +   "Nadeem Sarwar/fetch": "1.0.*",
Could you please return back this

2016-12-01 07:45 UTC, sergeyklay commented on README.md
> +# Moved from my personal repo to computerassistance gitlab - Nadeem
???

2016-12-01 07:45 UTC, sergeyklay commented on README.md
> +Fetch is licensed under the BSD License. See the LICENSE file for details..
Why?

2016-12-01 07:45 UTC, sergeyklay commented on src/Fetch/Message.php
> +/* testing edit */
???

2016-12-02 04:20 UTC, deemyboy commented
Hello.

I'm new to this so sorry if I've made any mistakes.

What should I do?

On 1 Dec 2016 7:45 am, "Serghei Iakovlev" <notifications@github.com> wrote:

> *@sergeyklay* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/tedious/Fetch/pull/184#pullrequestreview-10914005>:
>
> > @@ -26,24 +27,24 @@ backwards compatible.
>
>  ```
>  "require": {
> -  "tedivm/fetch": "0.6.*"
> +   "Nadeem Sarwar/fetch": "1.0.*",
>
> Could you please return back this
> ------------------------------
>
> In README.md
> <https://github.com/tedious/Fetch/pull/184#pullrequestreview-10914005>:
>
> > @@ -8,6 +8,7 @@
>  Fetch is a library for reading email and attachments, primarily using the POP
>  and IMAP protocols.
>
> +# Moved from my personal repo to computerassistance gitlab - Nadeem
>
> ???
> ------------------------------
>
> In README.md
> <https://github.com/tedious/Fetch/pull/184#pullrequestreview-10914005>:
>
> > @@ -64,4 +65,4 @@ by composer.
>
>  ## License
>
> -Fetch is licensed under the BSD License. See the LICENSE file for details.
> +Fetch is licensed under the BSD License. See the LICENSE file for details..
>
> Why?
> ------------------------------
>
> In src/Fetch/Message.php
> <https://github.com/tedious/Fetch/pull/184#pullrequestreview-10914005>:
>
> > @@ -1,5 +1,5 @@
>  <?php
> -
> +/* testing edit */
>
> ???
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/tedious/Fetch/pull/184#pullrequestreview-10914005>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACBKK7WmDE8v74fvjUNh3mbzGqq7jp4Qks5rDnsJgaJpZM4KzAjq>
> .
>

2022-11-28 11:33 UTC, closed without merging